name: CI Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Echo Token to .env
        run: echo ${{ secrets.TG_BOT_TOKEN }} >> .env

      - name: Run app.py
        run: python app.py
